# Change these first
owner: dnum-mi # Your GitHub organization or username, where this repository lives
repo: stats-sites-api # The name of this repository

sites:
  - name: Site Google
    url: https://www.google.com
  - name: C3 Site Personnes Décédées
    url: https://deces.matchid.io/search?q=pompidou+georges
    icon: https://avatars.githubusercontent.com/u/32673019?s=200&v=4
    method: GET
  - name: C3 Site IA Flash
    url: https://iaflash.fr/
  - name: Site Histovec
    url: https://histovec.interieur.gouv.fr/histovec
    expectedStatusCodes:
      - 200
  - name: Site SCAE RGA
    url: https://www.sca-rga.interieur.gouv.fr/
    method: GET
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000
  - name: Site ANTS
    url: https://ants.gouv.fr
    method: GET
    icon: https://ants.gouv.fr/logo-republique-francaise.svg
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000
  - name: Site telepoint
    url: https://mespoints.permisdeconduire.gouv.fr
    method: GET
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000    
  - name: C3 API Personnes décédées
    url: https://deces.matchid.io/deces/api/v1/search?q=pompidou%20georges&fuzzy=false
    method: GET
    icon: https://avatars.githubusercontent.com/u/32673019?s=200&v=4
    expectedStatusCodes:
      - 200
      - 400
    maxResponseTime: 3000
  - name: C3 API ROF v1 beta
    url: https://api-rof-bd.herokuapp.com/api/v1/operateurs_funeraires/healthcheck
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000
  - name: Base Gun
    url: https://basegun.interieur.gouv.fr
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /stats-sites-api
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://www.interieur.gouv.fr/var/miomcti/storage/images/media/mi/images/bloc-marque-minint/981901-1-fre-FR/Bloc-marque-minint_large.png
  name: Upptime - Disponibilité des sites et api
  theme: night
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introTitle: "**Disponibilité des Sites et API**"
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  introMessage: Retrouvez sur ce tableau de bord, les disponibilités des Sites et API 
 
  navbar:
    - title: Autre dashboard
      href: https://dnum-mi.github.io/dashlord
    - title: api.minint.fr
      href: http://api.minint.fr
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  activeIncidents: Incidents en cours
  allSystemsOperational: Tous les sytèmes sont opérationnels
  incidentReport: "Rapport d'incident #$NUMBER →"
  activeIncidentSummary: Ouvert le $DATE avec $POSTS posts
  incidentTitle: Détails de l'incident $NUMBER
  incidentDetails: Détails de l'incident
  incidentFixed: Résolu
  incidentOngoing: En cours
  incidentOpenedAt: Ouvert le
  incidentClosedAt: Fermé le
  incidentSubscribe: S'abonner aux mises à jour
  incidentViewOnGitHub: Voir sur GitHub
  incidentCommentSummary: Posté le $DATE par $AUTHOR
  incidentBack: ← Retour aux incidents
  pastIncidents: Incidents passés
  pastIncidentsResolved: Resolu en $MINUTES minutes avec $POSTS posts
  liveStatus: Statut temps réel
  overallUptime: "Disponibilité globale : $UPTIME"
  overallUptimeTitle: Disponibilité globale
  averageResponseTime: "Temps de réponse moyen : $TIMEms"
  averageResponseTimeTitle: Temps de réponse moyen
  sevelDayResponseTime: Temps de réponse sur 7 jours
  responseTimeMs: Temps de réponse (ms)
  up: Opérationnel
  down: Indisponible
  degraded: Dégradé
  ms: ms
  loading: Chargement
  navGitHub: GitHub
  footer: Cette page est [open source]($REPO), propulsée par [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Quota dépassé
  rateLimitExceededIntro: Vous avez dépassé le nombre de requêtes que vous pouvez faire en une heure, vous devez donc attendre avant de pouvoir accéder à nouveau au site. Vous pouvez également ajouter un GitHub Personal Access Token pour continuer à utiliser le site.
  rateLimitExceededWhatDoesErrorMean: Que veut dire cette erreur ?
  rateLimitExceededErrorMeaning: Ce site utilise l'API  de Github pour accéder au statut de notre API. Par défaut, Github autorise 60 requêtes par heure par IP, quota que vous avez dépassé.
  rateLimitExceededErrorHowCanFix: Comment réparer cela ?
  rateLimitExceededErrorFix: Vous pouvez attendre l'heure suivante et votre adresse IP sera débloquée. Vous pouvez également renseigner un GitHub Personal Access Token, qui vous donnera un nouveau quota de 5000 requêtes par heure.
  rateLimitExceededGeneratePAT: Voir comment générer un Personal Access Token
  rateLimitExceededHasSet: Vous avez un Personal Access Token renseigné.
  rateLimitExceededRemoveToken: Supprimer le token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copier/coller le token
  rateLimitExceededSaveToken: Enregistrer le token
  errorTitle: Une erreur s'est produite
  errorIntro: Oups ! Une erreur s'est produite en tentant de charger les derniers statuts de disponibilité.
  errorText: Veuillez réessayer dans quelques instants.
  errorHome: Retour à l'accueil

workflowSchedule:
  graphs: "*/60 * * * *"
  responseTime: "*/60 * * * *"
  staticSite: "*/60 * * * *"
  summary: "*/60 * * * *"
  updateTemplate: "*/60 * * * *"
  updates: "*/60 * * * *"
  uptime: "*/60 * * * *"
